"""Pure Telegram presentation functions fed by immutable view models."""

from .common import (
    MODE_NAMES,
    SESSION_BTN_BEGIN,
    SESSION_BTN_END,
    mode_buttons,
    reply_keyboard,
)
from .proxy import ProxyViewState, proxy_list_view, proxy_view
from .home import HomeViewState, home_button, home_view
from .dashboard import DashboardAccessViewState, dashboard_access_view
from .job import JobCardView, job_card_view
from .queue import (
    PendingQueueItemView,
    QueueItemView,
    QueueViewState,
    queue_view,
)
from .webdav import (
    BackupAttemptDetailView,
    BackupAttemptListItemView,
    BackupAttemptPageView,
    BackupFileItemView,
    WebDavConfigViewState,
    backup_attempt_detail_view,
    backup_attempt_page_view,
    webdav_delete_confirm_view,
    webdav_cfg_fields_view,
    webdav_cfg_lines,
    webdav_probe_view,
    webdav_write_confirm_view,
    webdav_write_result_view,
    webdav_required_policy_confirm_view,
    webdav_cfg_view,
)
from .tasks import (
    DurableQueueItemView,
    DurableQueuePageView,
    FailureItemView,
    JobDetailViewState,
    confirmation_view,
    batch_actions_view,
    durable_queue_view,
    failure_center_view,
    job_detail_view,
)
from .stats import stats_view
from .destination_profiles import (
    DestinationProfileView,
    destination_profile_detail_view,
    destination_profile_test_confirm_view,
    destination_profiles_view,
)

__all__ = [
    "MODE_NAMES",
    "SESSION_BTN_BEGIN",
    "SESSION_BTN_END",
    "mode_buttons",
    "reply_keyboard",
    "ProxyViewState",
    "proxy_view",
    "proxy_list_view",
    "HomeViewState",
    "home_view",
    "home_button",
    "DashboardAccessViewState",
    "dashboard_access_view",
    "JobCardView",
    "job_card_view",
    "QueueItemView",
    "PendingQueueItemView",
    "QueueViewState",
    "queue_view",
    "WebDavConfigViewState",
    "BackupAttemptListItemView",
    "BackupAttemptPageView",
    "BackupFileItemView",
    "BackupAttemptDetailView",
    "webdav_cfg_lines",
    "webdav_cfg_view",
    "webdav_cfg_fields_view",
    "backup_attempt_page_view",
    "backup_attempt_detail_view",
    "webdav_delete_confirm_view",
    "webdav_probe_view",
    "webdav_write_confirm_view",
    "webdav_write_result_view",
    "webdav_required_policy_confirm_view",
    "DurableQueueItemView",
    "DurableQueuePageView",
    "FailureItemView",
    "JobDetailViewState",
    "confirmation_view",
    "batch_actions_view",
    "durable_queue_view",
    "failure_center_view",
    "job_detail_view",
    "stats_view",
    "DestinationProfileView",
    "destination_profiles_view",
    "destination_profile_detail_view",
    "destination_profile_test_confirm_view",
]
